POST http://localhost:8000/auth/login 
Content-Type: application/json

{
  "email": "ben123@gmail.com"
}
### 

POST http://localhost:8000/auth/authenticate
Content-Type: application/json

{
  "email": "ben123@gmail.com", 
  "emailToken": "12972088"
}
###

GET http://localhost:8000/users 
###

GET http://localhost:8000/users/1
###

POST http://localhost:8000/users 
Content-Type: application/json

{
  "email": "derek123@gmail.com", 
  "name": "derek123",
  "username": "derek123"
}
###

PUT http://localhost:8000/users/5
Content-Type: application/json

{
  "bio": "john123", 
  "name": "john123",
  "image": "john123"
}
###

GET http://localhost:8000/tweets 
###

GET http://localhost:8000/tweets/2
###

POST http://localhost:8000/tweets 
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklkIjoxNX0.w0meAjJTwQPbZatntipVOVwi7dmLhqPy27wseYvfloU

{
  "content": "My third tweet", 
  "userId": 1
}
###

DELETE http://localhost:8000/tweets/1
###


